using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using LetMeSleep.Bootstrap;
using LetMeSleep.Content.Environment;
using LetMeSleep.Presentation;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;
using Object = UnityEngine.Object;

namespace LetMeSleep.Editor
{
    /// <summary>
    /// v0.3.0 per-map decoration (MAPA-SISTEMAS maps, extension point Decor). Reproducible from one JSON config
    /// (docs/v030/maps/decor-v030.json, generated by docs/v030/maps/decor_config.py):
    ///   -executeMethod LetMeSleep.Editor.V030SceneTools.Run -v030Steps decor [-v030DecorConfig &lt;abs.json&gt;]
    /// For every map it loads the map prefab into a scratch scene, places the v0.3.0 library props (explicit items and
    /// seeded scatters), and keeps only placements that
    /// - rest on an allowed surface found by a downward raycast (map colliders plus temporary colliders on visual floors
    ///   such as teak decks or floorboards, never saved), within the slope/footprint tolerance of the prop;
    /// - stay out of every keep-out of <see cref="HiggsfieldDecorClearance"/> (human routes, portals, stairs, spawns,
    ///   objectives and their targets) and inside PlayBounds;
    /// - do not intersect solid map geometry or other decor.
    /// Items search a small spiral around their authored spot before being rejected. The result is saved as
    /// HiggsfieldDecor/&lt;mapId&gt;/&lt;mapId&gt;-Decor.prefab (identity root, nested library prefabs, lamp lights and a
    /// <see cref="HiggsfieldDecorDressing"/> for halos/flicker), re-validated from the saved asset (catalog contract,
    /// clearance and 2 cm surface support) and assigned to HiggsfieldMapCatalog.Entry.Decor. The map prefabs, their
    /// colliders, navigation and ContentHash are never modified. A JSON receipt lists accepted and rejected placements.
    /// </summary>
    public static class HiggsfieldDecorBuilder
    {
        public const string CatalogPath = "Assets/LetMeSleep/Presentation/Generated/HiggsfieldFiveMaps.asset";
        public const string DefaultConfig = "docs/v030/maps/decor-v030.json";
        public const float SupportTolerance = 0.02f;
        public const float OpeningMargin = 0.15f;
        const string Separator = "__";

        // ---------- Config ----------
        public sealed class Config
        {
            public string schema;
            public string outputRoot;
            public string kit;
            public MapConfig[] maps;
        }
        public sealed class MapConfig
        {
            public string mapId;
            public string floorPattern, pathPattern, waterPattern, excludePattern;
            // r2 (director #5): windows and doors (renderer names) are keep-outs for wall props, OpeningMargin around the frame.
            public string openingPattern;
            // Surfaces that never count as plain wall behind a wall prop (frames meshed with the whole cabin); default openingPattern.
            public string openingHitPattern;
            public float? waterY;
            public int maxLights = 8;
            public Item[] items = Array.Empty<Item>();
            public Scatter[] scatters = Array.Empty<Scatter>();
        }
        public sealed class Item
        {
            public string id, group, prop, mount = "floor", on, surfacePattern, face;
            public float[] at, dir, scale, faceAt;
            public float? yHint, yaw, height, waterOffset;
            public float search = 0.8f, sink;
            // r2: prop "Light" places only a shadowless decor light at the item position (e.g. a map lamp switched on).
            public bool required, allowOverlap, organic;
            public LightSpec light;
            public HaloSpec halo;
        }
        public sealed class Scatter
        {
            public string id, group, near = null, mount = "floor", surfacePattern;
            public Dictionary<string, float> props;
            public float[] min, max, center, scale = { 0.85f, 1.15f };
            public float radius, radiusMin, nearMin = 0.8f, nearMax = 2.2f, minSpacing = 1.5f, sink = 0.012f;
            // r2 (director #6): per-prop scale range overriding the scatter scale (e.g. flower groups >= 0.4 m tall).
            public Dictionary<string, float[]> propScale;
            public float? yHint, waterOffset;
            public int count, attempts, seed = 1;
        }
        public sealed class LightSpec { public string color = "#FFB347", anchor = "light"; public float intensity = 1.6f, range = 4.5f, flicker; public float[] offset; }
        public sealed class HaloSpec { public string color = "#FFB347", anchor = "light"; public float size = 0.8f, alpha = 0.35f, intensity = 1f; public float[] offset; }

        static readonly HashSet<string> OrganicProps = new HashSet<string>(StringComparer.Ordinal)
        { "Bush", "Fern", "FlowersWhite", "FlowersYellow", "Mushrooms", "Reeds", "RockCluster", "TreeStump", "Firewood", "LogBench" };

        public static void BuildFromConfig(string output)
        {
            string repository = Path.GetFullPath(Path.Combine(Application.dataPath, "../.."));
            string configPath = V030PropLibraryImporter.Argument("-v030DecorConfig") ?? Path.Combine(repository, DefaultConfig);
            var config = JsonConvert.DeserializeObject<Config>(File.ReadAllText(configPath));
            Need(config != null && config.schema == "lms.decor.v030/1" && config.maps != null, "Unexpected decor config schema: " + configPath);
            Need(config.outputRoot != null && config.outputRoot.StartsWith("Assets/LetMeSleep/Content/Environment/", StringComparison.Ordinal), "Decor output must live under Content/Environment.");
            var receipt = new JObject { ["utc"] = DateTime.UtcNow.ToString("o"), ["config"] = configPath, ["unity"] = Application.unityVersion };
            var mapsReport = new JArray();
            // Asset paths, not objects: every map opens a fresh scene, which unloads assets loaded before it.
            var built = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (var mapConfig in config.maps)
            {
                var report = BuildMap(config, mapConfig, out var prefabPath);
                built[mapConfig.mapId] = prefabPath;
                mapsReport.Add(report);
            }
            receipt["maps"] = mapsReport;
            // Assign after every map built: a fresh scene unloads the catalog loaded earlier.
            EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);
            var catalog = AssetDatabase.LoadAssetAtPath<HiggsfieldMapCatalog>(CatalogPath);
            Need(catalog, "Catalog missing");
            var serialized = new SerializedObject(catalog);
            var entries = serialized.FindProperty("entries");
            for (int i = 0; i < entries.arraySize; i++)
            {
                var entry = entries.GetArrayElementAtIndex(i);
                string id = entry.FindPropertyRelative("MapId").stringValue;
                if (!built.TryGetValue(id, out var prefabPath)) continue;
                var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(prefabPath);
                Need(prefab, "Saved decor missing: " + prefabPath);
                entry.FindPropertyRelative("Decor").objectReferenceValue = prefab;
            }
            serialized.ApplyModifiedPropertiesWithoutUndo();
            EditorUtility.SetDirty(catalog);
            AssetDatabase.SaveAssets();
            catalog.Validate();
            receipt["catalog"] = CatalogPath;
            File.WriteAllText(Path.Combine(output, "decor-receipt.json"), receipt.ToString(Formatting.Indented) + "\n");
            Debug.Log("LMS_DECOR_BUILT " + string.Join(", ", built.Keys));
        }

        // ---------- One map ----------
        sealed class Placed { public string id, prop, mount; public GameObject go; public Bounds bounds; public List<Collider> temp = new List<Collider>(); public string scatter; public bool flat; }

        sealed class Context
        {
            public MapConfig map;
            public EnvironmentMapDefinition instance;
            public List<HiggsfieldDecorClearance.Keepout> keepouts;
            public HashSet<Collider> mapColliders = new HashSet<Collider>();
            public List<Placed> placed = new List<Placed>();
            public Dictionary<string, Placed> byId = new Dictionary<string, Placed>(StringComparer.Ordinal);
            public Regex floor, path, water, exclude;
            public List<Bounds> waterAreas = new List<Bounds>();
            public List<(string name, Bounds box)> openings = new List<(string, Bounds)>();
            public Regex opening;
            public GameObject root;
            public Dictionary<string, Transform> groups = new Dictionary<string, Transform>(StringComparer.Ordinal);
            public int lights;
            public JArray rejected = new JArray();
        }

        static JObject BuildMap(Config config, MapConfig mapConfig, out string prefabPath)
        {
            var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);
            var catalog = AssetDatabase.LoadAssetAtPath<HiggsfieldMapCatalog>(CatalogPath);
            var entry = catalog.Resolve(mapConfig.mapId);
            var kit = AssetDatabase.LoadAssetAtPath<HiggsfieldAtmosphereKit>(config.kit);
            Need(kit, "Atmosphere kit missing: " + config.kit);
            var ctx = new Context { map = mapConfig };
            ctx.instance = (EnvironmentMapDefinition)PrefabUtility.InstantiatePrefab(entry.Prefab, scene);
            ctx.floor = new Regex(mapConfig.floorPattern ?? "^$");
            ctx.path = new Regex(mapConfig.pathPattern ?? "^$");
            ctx.water = new Regex(mapConfig.waterPattern ?? "^$");
            ctx.exclude = new Regex(mapConfig.excludePattern ?? "^$");
            ctx.opening = new Regex(mapConfig.openingHitPattern ?? mapConfig.openingPattern ?? "^$");
            ctx.openings = Openings(ctx.instance, new Regex(mapConfig.openingPattern ?? "^$"));
            // Map geometry only: the invisible play-area walls and ceiling (_LMS_ArtificialBoundaries_v1) and triggers are
            // neither support nor obstacles for decoration.
            foreach (var collider in ctx.instance.GetComponentsInChildren<Collider>(true))
                if (!collider.isTrigger && !IsBoundary(collider.transform)) ctx.mapColliders.Add(collider);
            // Visual floors without colliders (teak decks, floorboards, cobbles) support decor exactly where it is seen.
            var surfacePatterns = new List<Regex> { ctx.floor, ctx.path };
            foreach (var item in mapConfig.items ?? Array.Empty<Item>()) if (!string.IsNullOrEmpty(item.surfacePattern)) surfacePatterns.Add(new Regex(item.surfacePattern));
            foreach (var renderer in ctx.instance.GetComponentsInChildren<MeshRenderer>(true))
            {
                if (renderer.GetComponent<Collider>()) continue;
                var filter = renderer.GetComponent<MeshFilter>();
                if (!filter || !filter.sharedMesh) continue;
                if (ctx.water.IsMatch(renderer.name)) { ctx.waterAreas.Add(renderer.bounds); continue; }
                if (!surfacePatterns.Any(p => p.IsMatch(renderer.name))) continue;
                var collider = renderer.gameObject.AddComponent<MeshCollider>();
                collider.sharedMesh = filter.sharedMesh;
                ctx.mapColliders.Add(collider);
            }
            foreach (var skinned in ctx.instance.GetComponentsInChildren<SkinnedMeshRenderer>(true))
                if (ctx.water.IsMatch(skinned.name)) ctx.waterAreas.Add(skinned.bounds);
            Physics.SyncTransforms();
            ctx.keepouts = HiggsfieldDecorClearance.Build(ctx.instance);
            ctx.root = new GameObject(mapConfig.mapId + "-Decor");
            SceneManager.MoveGameObjectToScene(ctx.root, scene);

            var accepted = new JArray();
            foreach (var item in mapConfig.items ?? Array.Empty<Item>())
            {
                if (item.prop == "Light")
                {
                    Need(item.light != null && item.at != null && item.at.Length == 3, "Light items need a light and an [x, y, z] position: " + item.id);
                    AttachLightAt(ctx, item);
                    accepted.Add(new JObject { ["id"] = item.id, ["prop"] = "Light", ["position"] = new JArray(item.at[0], item.at[1], item.at[2]) });
                    continue;
                }
                var placed = PlaceItem(ctx, item, out string reason);
                if (placed == null)
                {
                    ctx.rejected.Add(new JObject { ["id"] = item.id, ["prop"] = item.prop, ["reason"] = reason });
                    Need(!item.required, "Required decor item could not be placed: " + mapConfig.mapId + "/" + item.id + ": " + reason);
                    continue;
                }
                accepted.Add(Describe(placed));
                AttachLightAndHalo(ctx, placed, item.light, item.halo, kit);
            }
            foreach (var scatter in mapConfig.scatters ?? Array.Empty<Scatter>())
            {
                int placedCount = RunScatter(ctx, scatter, accepted);
                ctx.rejected.Add(new JObject { ["scatter"] = scatter.id, ["placed"] = placedCount, ["requested"] = scatter.count });
            }
            Need(ctx.lights <= Math.Min(mapConfig.maxLights, HiggsfieldMapCatalog.MaximumDecorLights), "Too many decor lights: " + mapConfig.mapId);

            // Dressing (halos, flicker) and cleanup of temporary colliders before saving.
            var dressing = ctx.root.AddComponent<HiggsfieldDecorDressing>();
            dressing.Kit = kit;
            dressing.Halos = pendingHalos.ToArray();
            dressing.Flickers = pendingFlickers.ToArray();
            pendingHalos.Clear(); pendingFlickers.Clear();
            foreach (var placed in ctx.placed) foreach (var collider in placed.temp) if (collider) Object.DestroyImmediate(collider);
            string folder = config.outputRoot + "/" + mapConfig.mapId;
            EnsureFolder(folder);
            prefabPath = folder + "/" + mapConfig.mapId + "-Decor.prefab";
            var savedPrefab = PrefabUtility.SaveAsPrefabAsset(ctx.root, prefabPath, out bool success);
            Need(success && savedPrefab, "Could not save " + prefabPath);
            HiggsfieldMapCatalog.ValidateDecor(savedPrefab, mapConfig.mapId);
            int savedRenderers = savedPrefab.GetComponentsInChildren<Renderer>(true).Length;
            var counts = new JObject();
            foreach (var group in ctx.placed.GroupBy(p => p.prop).OrderBy(g => g.Key)) counts[group.Key] = group.Count();
            int placedTotal = ctx.placed.Count, lightTotal = ctx.lights;

            // Re-validate from the saved asset under a fresh map instance.
            var problems = ValidateSaved(AssetDatabase.GetAssetPath(entry.Prefab), prefabPath, mapConfig);
            Need(problems.Count == 0, "Saved decor failed validation for " + mapConfig.mapId + ":\n" + string.Join("\n", problems));
            return new JObject
            {
                ["mapId"] = mapConfig.mapId, ["prefab"] = prefabPath, ["placed"] = placedTotal, ["lights"] = lightTotal,
                ["renderers"] = savedRenderers, ["counts"] = counts,
                ["accepted"] = accepted, ["rejected"] = ctx.rejected
            };
        }

        static readonly List<HiggsfieldDecorDressing.Halo> pendingHalos = new List<HiggsfieldDecorDressing.Halo>();
        static readonly List<HiggsfieldDecorDressing.Flicker> pendingFlickers = new List<HiggsfieldDecorDressing.Flicker>();

        static JObject Describe(Placed placed) => new JObject
        {
            ["id"] = placed.id, ["prop"] = placed.prop, ["mount"] = placed.mount,
            ["position"] = new JArray(Math.Round(placed.go.transform.position.x, 3), Math.Round(placed.go.transform.position.y, 3), Math.Round(placed.go.transform.position.z, 3)),
            ["yaw"] = Math.Round(placed.go.transform.eulerAngles.y, 1)
        };

        // ---------- Placement ----------
        static Placed PlaceItem(Context ctx, Item item, out string reason)
        {
            reason = null;
            Need(!string.IsNullOrEmpty(item.id) && !ctx.byId.ContainsKey(item.id), "Decor item id missing or duplicated: " + item.id);
            var prefab = PropPrefab(item.prop);
            Need(item.at != null && (item.at.Length == 2 || item.at.Length == 3), "Item position [x,z] or [x,y,z] required: " + item.id);
            float x = item.at[0], z = item.at[item.at.Length - 1];
            float? yHint = item.yHint ?? (item.at.Length == 3 ? item.at[1] : (float?)null);
            Vector3 scale = item.scale == null ? Vector3.one : item.scale.Length == 1 ? Vector3.one * item.scale[0] : new Vector3(item.scale[0], item.scale[1], item.scale[2]);
            bool organic = item.organic || OrganicProps.Contains(item.prop);
            string last = "no candidate";
            if (item.mount == "wall" && item.dir == null)
            {
                // No authored direction (rotated buildings): try the nearest walls around the spot, closest first.
                Need(yHint.HasValue && item.height.HasValue, "Wall items need a y hint and height: " + item.id);
                foreach (var offset in Spiral(item.search, 0.25f))
                {
                    var origin = new Vector3(x + offset.x, yHint.Value + item.height.Value, z + offset.y);
                    var walls = new List<(float distance, Vector2 dir)>();
                    for (int k = 0; k < 24; k++)
                    {
                        float a = k * Mathf.PI * 2f / 24f;
                        var d = new Vector3(Mathf.Cos(a), 0, Mathf.Sin(a));
                        if (Cast(ctx, origin, d, 3f, null, out RaycastHit hit) && Mathf.Abs(hit.normal.y) < 0.2f) walls.Add((hit.distance, new Vector2(d.x, d.z)));
                    }
                    foreach (var wall in walls.OrderBy(w => w.distance))
                    {
                        var placed = TryPlace(ctx, prefab, item.prop, item.id, item.group ?? "Decor", "wall", origin.x, origin.z, yHint, 0f, scale, organic,
                            item.sink, new[] { wall.dir.x, wall.dir.y }, item.height, null, item.surfacePattern, null, item.allowOverlap, null, out last);
                        if (placed != null) return placed;
                    }
                }
                reason = last;
                return null;
            }
            // Spiral search around the authored spot (0 first).
            foreach (var offset in Spiral(item.search, 0.2f))
            {
                float px = x + offset.x, pz = z + offset.y;
                float yaw = item.yaw ?? 0f;
                if (item.faceAt != null) yaw = Mathf.Atan2(item.faceAt[0] - px, item.faceAt[1] - pz) * Mathf.Rad2Deg + (item.yaw ?? 0f);
                var placed = TryPlace(ctx, prefab, item.prop, item.id, item.group ?? "Decor", item.mount, px, pz, yHint, yaw, scale, organic,
                    item.sink, item.dir, item.height, item.on, item.surfacePattern, item.waterOffset, item.allowOverlap, null, out last);
                if (placed != null) return placed;
            }
            reason = last;
            return null;
        }

        static int RunScatter(Context ctx, Scatter scatter, JArray accepted)
        {
            Need(scatter.props != null && scatter.props.Count > 0 && scatter.count > 0, "Scatter needs props and count: " + scatter.id);
            var random = new System.Random(scatter.seed);
            var names = scatter.props.Keys.OrderBy(k => k, StringComparer.Ordinal).ToArray();
            float total = names.Sum(n => scatter.props[n]);
            int attempts = scatter.attempts > 0 ? scatter.attempts : scatter.count * 40;
            int placedCount = 0, index = 0;
            var mine = new List<Vector3>();
            for (int attempt = 0; attempt < attempts && placedCount < scatter.count; attempt++)
            {
                float px, pz;
                if (scatter.center != null)
                {
                    double inner = Math.Max(0, Math.Min(scatter.radiusMin, scatter.radius)) / Math.Max(1e-4, scatter.radius);
                    double angle = random.NextDouble() * Math.PI * 2, r = Math.Sqrt(inner * inner + random.NextDouble() * (1 - inner * inner)) * scatter.radius;
                    px = scatter.center[0] + (float)(Math.Cos(angle) * r); pz = scatter.center[1] + (float)(Math.Sin(angle) * r);
                }
                else
                {
                    px = Mathf.Lerp(scatter.min[0], scatter.max[0], (float)random.NextDouble());
                    pz = Mathf.Lerp(scatter.min[1], scatter.max[1], (float)random.NextDouble());
                }
                double pick = random.NextDouble() * total; string prop = names[names.Length - 1];
                foreach (var name in names) { pick -= scatter.props[name]; if (pick <= 0) { prop = name; break; } }
                float yaw = (float)random.NextDouble() * 360f;
                var range = scatter.propScale != null && scatter.propScale.TryGetValue(prop, out var custom) ? custom : scatter.scale;
                float s = Mathf.Lerp(range[0], range[1], (float)random.NextDouble());
                var candidate = new Vector3(px, 0, pz);
                if (mine.Any(p => (new Vector2(p.x - px, p.z - pz)).sqrMagnitude < scatter.minSpacing * scatter.minSpacing)) continue;
                if (scatter.near == "path" && !NearSurface(ctx, px, pz, scatter.yHint, ctx.path, scatter.nearMin, scatter.nearMax)) continue;
                if (scatter.near == "water" && !NearWater(ctx, px, pz, scatter.nearMin, scatter.nearMax)) continue;
                string id = scatter.id + "-" + index.ToString("00");
                var placed = TryPlace(ctx, PropPrefab(prop), prop, id, scatter.group ?? "Decor_Scatter", scatter.mount, px, pz, scatter.yHint, yaw,
                    Vector3.one * s, OrganicProps.Contains(prop), scatter.sink, null, null, null, scatter.surfacePattern, scatter.waterOffset, false,
                    scatter.near == "path" ? ctx.path : null, out _);
                if (placed == null) continue;
                placed.scatter = scatter.id;
                mine.Add(placed.go.transform.position);
                accepted.Add(Describe(placed));
                placedCount++; index++;
            }
            return placedCount;
        }

        static Placed TryPlace(Context ctx, GameObject prefab, string prop, string id, string group, string mount, float px, float pz, float? yHint,
            float yaw, Vector3 scale, bool organic, float sink, float[] dir, float? height, string on, string surfacePattern, float? waterOffset,
            bool allowOverlap, Regex forbidSupport, out string reason)
        {
            reason = null;
            var surface = string.IsNullOrEmpty(surfacePattern) ? ctx.floor : new Regex(surfacePattern);
            Vector3 position; Quaternion rotation = Quaternion.Euler(0, yaw, 0);
            Placed target = null;
            switch (mount)
            {
                case "floor":
                case "on":
                {
                    if (mount == "on")
                    {
                        // Stacked on a placed item: centred on where that item actually landed (it may have searched).
                        if (on == null || !ctx.byId.TryGetValue(on, out target)) { reason = "stack target not placed: " + on; return null; }
                        px = target.go.transform.position.x;
                        pz = target.go.transform.position.z;
                        yHint = target.bounds.max.y;
                    }
                    if (!Down(ctx, px, pz, yHint, mount == "on" ? target : null, out RaycastHit hit, out string what)) { reason = "no surface below (" + what + ")"; return null; }
                    if (mount == "floor" && !surface.IsMatch(hit.collider.name)) { reason = "surface not allowed: " + hit.collider.name; return null; }
                    if (forbidSupport != null && forbidSupport.IsMatch(hit.collider.name)) { reason = "on a path"; return null; }
                    if (ctx.exclude.IsMatch(hit.collider.name)) { reason = "excluded surface " + hit.collider.name; return null; }
                    float slope = Vector3.Angle(hit.normal, Vector3.up);
                    if (slope > (organic ? 32f : 14f)) { reason = "slope " + slope.ToString("0"); return null; }
                    position = hit.point - Vector3.up * Mathf.Clamp(sink, 0f, SupportTolerance * 0.75f);
                    break;
                }
                case "water":
                {
                    Need(ctx.map.waterY.HasValue, "waterY required for water mounts: " + ctx.map.mapId);
                    float y = ctx.map.waterY.Value + (waterOffset ?? 0f);
                    if (!OverWater(ctx, px, pz)) { reason = "not over water"; return null; }
                    position = new Vector3(px, y, pz);
                    break;
                }
                case "wall":
                {
                    Need(dir != null && dir.Length == 2 && yHint.HasValue && height.HasValue, "Wall items need dir [x,z], y hint and height: " + id);
                    var origin = new Vector3(px, yHint.Value + height.Value, pz);
                    var direction = new Vector3(dir[0], 0, dir[1]).normalized;
                    if (!Cast(ctx, origin, direction, 4f, null, out RaycastHit hit)) { reason = "no wall"; return null; }
                    if (Mathf.Abs(hit.normal.y) > 0.2f) { reason = "wall not vertical"; return null; }
                    Vector3 normal = new Vector3(hit.normal.x, 0, hit.normal.z).normalized;
                    position = hit.point + normal * 0.012f;
                    position.y = origin.y;
                    rotation = Quaternion.LookRotation(normal, Vector3.up);
                    break;
                }
                case "ceiling":
                {
                    Need(yHint.HasValue, "Ceiling items need a y hint: " + id);
                    if (!Cast(ctx, new Vector3(px, yHint.Value + 0.5f, pz), Vector3.up, 4f, null, out RaycastHit hit)) { reason = "no ceiling"; return null; }
                    position = hit.point;
                    break;
                }
                default: throw new InvalidOperationException("Unknown mount " + mount + " for " + id);
            }

            var go = (GameObject)PrefabUtility.InstantiatePrefab(prefab, ctx.root.scene);
            go.name = prop + Separator + id + Separator + mount;
            go.transform.SetParent(Group(ctx, group), false);
            go.transform.localScale = scale;
            if (mount == "ceiling")
            {
                // Hang from the hit: the pivot is the lowest vertex, the prop's top touches the ceiling.
                float h = PrefabBounds(go).size.y;
                position.y -= h;
            }
            go.transform.SetPositionAndRotation(position, rotation);
            if (mount == "wall")
            {
                // Pivot = centre of the prop's depth: push it out by half the depth so the back sits on the wall. The depth is
                // measured unrotated (front = +Z): the world AABB of a prop on a diagonal wall would also count its width.
                go.transform.rotation = Quaternion.identity;
                float depth = PrefabBounds(go).size.z;
                go.transform.rotation = rotation;
                Vector3 normal = rotation * Vector3.forward;
                go.transform.position += normal * (depth * 0.5f + 0.004f - 0.012f);
            }
            Physics.SyncTransforms();
            Bounds bounds = PrefabBounds(go);
            string problem = Check(ctx, go, bounds, mount, organic, allowOverlap, target);
            if (problem == null && mount == "wall") problem = OpeningClash(ctx.openings, bounds) ?? WallContact(ctx, go, bounds);
            if (problem == null && (mount == "floor" || mount == "on") && prop != "LilyPads")
                problem = Footprint(ctx, go, bounds, organic, target);
            if (problem != null) { Object.DestroyImmediate(go); reason = problem; return null; }
            var placed = new Placed { id = id, prop = prop, mount = mount, go = go, bounds = bounds, flat = bounds.size.y <= HiggsfieldDecorClearance.WalkableFlatHeight };
            // Temporary colliders let later items stack on this one; removed before the prefab is saved.
            foreach (var filter in go.GetComponentsInChildren<MeshFilter>(true))
            {
                var collider = filter.gameObject.AddComponent<MeshCollider>();
                collider.sharedMesh = filter.sharedMesh;
                placed.temp.Add(collider);
            }
            Physics.SyncTransforms();
            ctx.placed.Add(placed);
            ctx.byId[id] = placed;
            return placed;
        }

        static string Check(Context ctx, GameObject go, Bounds bounds, string mount, bool organic, bool allowOverlap, Placed target)
        {
            var play = ctx.instance.PlayBounds;
            if (!play.Contains(bounds.min) || !play.Contains(bounds.max)) return "outside PlayBounds";
            var violation = HiggsfieldDecorClearance.FirstViolation(bounds, ctx.keepouts, (a, b) => Separated(ctx.mapColliders, a, b));
            if (violation != null) return "keep-out " + violation.Kind + " " + violation.Id;
            if (mount == "floor" || mount == "on" || mount == "water")
            {
                // Solid map geometry inside the prop volume (walls, furniture, trunks): lift above the contact and shrink.
                float shrink = organic ? 0.55f : 0.8f;
                float bottom = bounds.min.y + Mathf.Max(0.1f, bounds.size.y * (organic ? 0.35f : 0.15f));
                if (bottom < bounds.max.y - 0.02f)
                {
                    var center = new Vector3(bounds.center.x, (bottom + bounds.max.y) * 0.5f, bounds.center.z);
                    var half = new Vector3(bounds.extents.x * shrink, (bounds.max.y - bottom) * 0.5f, bounds.extents.z * shrink);
                    foreach (var hit in Physics.OverlapBox(center, half, Quaternion.identity, ~0, QueryTriggerInteraction.Collide))
                        if (ctx.mapColliders.Contains(hit) && !ctx.floor.IsMatch(hit.name)) return "intersects " + hit.name;
                }
            }
            if (!allowOverlap)
            {
                var shrunk = new Bounds(bounds.center, Vector3.Scale(bounds.size, new Vector3(0.85f, 0.9f, 0.85f)));
                foreach (var other in ctx.placed)
                {
                    if (other == target || other.flat) continue;
                    if (shrunk.Intersects(other.bounds)) return "overlaps decor " + other.id;
                }
            }
            return null;
        }

        /// <summary>
        /// A wall prop needs plain wall behind all of it and <see cref="OpeningMargin"/> around it: a grid of rays from just in
        /// front of the prop, over its back face grown by the margin, must hit a vertical map surface that is not a window,
        /// door or frame (director r2 #5: a shelf crossed a cottage window).
        /// </summary>
        static string WallContact(Context ctx, GameObject go, Bounds bounds)
        {
            Vector3 forward = go.transform.forward, right = go.transform.right;
            float half = Mathf.Abs(Vector3.Dot(bounds.extents, new Vector3(Mathf.Abs(right.x), Mathf.Abs(right.y), Mathf.Abs(right.z)))) + OpeningMargin;
            float halfHeight = bounds.extents.y + OpeningMargin;
            Vector3 mid = new Vector3(go.transform.position.x, bounds.center.y, go.transform.position.z);
            for (int i = 0; i <= 4; i++)
                for (int j = 0; j <= 3; j++)
                {
                    float t = Mathf.Lerp(-half, half, i / 4f), h = Mathf.Lerp(-halfHeight, halfHeight, j / 3f);
                    Vector3 origin = mid + right * t + Vector3.up * h + forward * 0.05f;
                    if (!Cast(ctx, origin, -forward, 0.2f, null, out RaycastHit hit)) return "no wall behind the prop (window, edge or opening within " + OpeningMargin + " m)";
                    if (Mathf.Abs(hit.normal.y) > 0.2f) return "wall behind not vertical at " + hit.collider.name;
                    if (ctx.opening.IsMatch(hit.collider.name)) return "over an opening " + hit.collider.name;
                }
            return null;
        }

        /// <summary>Window and door renderers of the map (names matching the map's openingPattern), grown by the margin.</summary>
        public static List<(string name, Bounds box)> Openings(EnvironmentMapDefinition map, Regex pattern)
        {
            var result = new List<(string, Bounds)>();
            foreach (var renderer in map.GetComponentsInChildren<Renderer>(true))
            {
                if (!pattern.IsMatch(renderer.name)) continue;
                var box = renderer.bounds; box.Expand(2f * OpeningMargin);
                result.Add((renderer.name, box));
            }
            return result;
        }

        public static string OpeningClash(List<(string name, Bounds box)> openings, Bounds bounds)
        {
            foreach (var (name, box) in openings) if (box.Intersects(bounds)) return "within " + OpeningMargin + " m of the opening " + name;
            return null;
        }

        /// <summary>Every footprint corner must find the same kind of surface within the prop's tolerance.</summary>
        static string Footprint(Context ctx, GameObject go, Bounds bounds, bool organic, Placed target)
        {
            float tolerance = organic ? 0.16f : 0.05f;
            float y = go.transform.position.y;
            // Stacked props may be turned against the one below: test well inside their footprint.
            float inset = target != null ? 0.45f : organic ? 0.3f : 0.12f;
            var corners = new[] { new Vector2(-1, -1), new Vector2(1, -1), new Vector2(1, 1), new Vector2(-1, 1) };
            foreach (var c in corners)
            {
                float cx = Mathf.Lerp(bounds.center.x, bounds.center.x + c.x * bounds.extents.x, 1f - inset);
                float cz = Mathf.Lerp(bounds.center.z, bounds.center.z + c.y * bounds.extents.z, 1f - inset);
                if (!Down(ctx, cx, cz, y + 0.02f, target, out RaycastHit hit, out _, go)) return "footprint over a void";
                if (Mathf.Abs(hit.point.y - y) > tolerance + 0.02f) return "uneven footprint " + (hit.point.y - y).ToString("0.00");
            }
            return null;
        }

        /// <summary>
        /// Nearest surface straight below (x, z): a map collider (real or temporary visual floor) or, when stacking, the
        /// target's temporary collider. Another decor item in between means the spot is taken.
        /// </summary>
        static bool Down(Context ctx, float x, float z, float? yHint, Placed onlyTarget, out RaycastHit best, out string what, GameObject ignore = null)
        {
            best = default; what = "nothing";
            float top = yHint.HasValue ? yHint.Value + 1.2f : ctx.instance.PlayBounds.max.y + 2f;
            var hits = Physics.RaycastAll(new Vector3(x, top, z), Vector3.down, top - ctx.instance.PlayBounds.min.y + 5f, ~0, QueryTriggerInteraction.Ignore);
            Array.Sort(hits, (a, b) => a.distance.CompareTo(b.distance));
            foreach (var hit in hits)
            {
                if (ignore && hit.collider.transform.IsChildOf(ignore.transform)) continue;
                if (ctx.mapColliders.Contains(hit.collider) || (onlyTarget != null && onlyTarget.temp.Contains(hit.collider)))
                {
                    best = hit; what = hit.collider.name; return true;
                }
                if (ctx.placed.Any(p => p.temp.Contains(hit.collider))) { what = "other decor below"; return false; }
            }
            return false;
        }

        public static bool IsBoundary(Transform t)
        {
            for (; t; t = t.parent) if (t.name == "_LMS_ArtificialBoundaries_v1") return true;
            return false;
        }

        /// <summary>
        /// True when a wall (a map surface facing sideways) lies between the two points; ground slopes do not count. Both
        /// directions are cast because mesh colliders are one-sided.
        /// </summary>
        public static bool Separated(ICollection<Collider> map, Vector3 a, Vector3 b)
        {
            Vector3 d = b - a; float length = d.magnitude;
            if (length < 1e-3f) return false;
            foreach (var hit in Physics.RaycastAll(a, d / length, length, ~0, QueryTriggerInteraction.Ignore))
                if (map.Contains(hit.collider) && Mathf.Abs(hit.normal.y) < .5f) return true;
            foreach (var hit in Physics.RaycastAll(b, -d / length, length, ~0, QueryTriggerInteraction.Ignore))
                if (map.Contains(hit.collider) && Mathf.Abs(hit.normal.y) < .5f) return true;
            return false;
        }

        static bool Cast(Context ctx, Vector3 origin, Vector3 direction, float distance, GameObject ignore, out RaycastHit best)
        {
            best = default; float nearest = float.MaxValue; bool found = false;
            foreach (var hit in Physics.RaycastAll(origin, direction, distance, ~0, QueryTriggerInteraction.Ignore))
            {
                if (!ctx.mapColliders.Contains(hit.collider)) continue;
                if (hit.distance < nearest) { nearest = hit.distance; best = hit; found = true; }
            }
            return found;
        }

        static bool NearSurface(Context ctx, float x, float z, float? yHint, Regex pattern, float min, float max)
        {
            for (int i = 0; i < 8; i++)
            {
                float angle = i * Mathf.PI / 4f;
                foreach (float r in new[] { min, (min + max) * 0.5f, max })
                    if (Down(ctx, x + Mathf.Cos(angle) * r, z + Mathf.Sin(angle) * r, yHint, null, out var hit, out _) && pattern.IsMatch(hit.collider.name))
                        return true;
            }
            return false;
        }

        static bool OverWater(Context ctx, float x, float z)
        {
            if (!ctx.map.waterY.HasValue || !ctx.waterAreas.Any(b => x >= b.min.x && x <= b.max.x && z >= b.min.z && z <= b.max.z)) return false;
            float water = ctx.map.waterY.Value;
            if (Down(ctx, x, z, water + 2f, null, out var hit, out _) && hit.point.y > water - 0.05f) return false;
            return true;
        }

        static bool NearWater(Context ctx, float x, float z, float min, float max)
        {
            for (int i = 0; i < 8; i++)
            {
                float angle = i * Mathf.PI / 4f;
                foreach (float r in new[] { min, max })
                    if (OverWater(ctx, x + Mathf.Cos(angle) * r, z + Mathf.Sin(angle) * r)) return true;
            }
            return false;
        }

        static void AttachLightAndHalo(Context ctx, Placed placed, LightSpec light, HaloSpec halo, HiggsfieldAtmosphereKit kit)
        {
            if (light != null)
            {
                var anchor = Anchor(placed.go, light.anchor);
                var go = new GameObject("DecorLight_" + placed.id);
                go.transform.SetParent(anchor, false);
                if (light.offset != null) go.transform.localPosition = new Vector3(light.offset[0], light.offset[1], light.offset[2]);
                var component = go.AddComponent<Light>();
                component.type = LightType.Point;
                Need(ColorUtility.TryParseHtmlString(light.color, out var color), "Bad light color " + light.color);
                component.color = color;
                component.intensity = light.intensity;
                component.range = Mathf.Min(light.range, HiggsfieldMapCatalog.MaximumDecorLightRange);
                component.shadows = LightShadows.None;
                component.bounceIntensity = 0f;
                component.renderMode = LightRenderMode.Auto;
                component.cullingMask &= ~(1 << 30);
                component.lightmapBakeType = LightmapBakeType.Realtime;
                ctx.lights++;
                if (light.flicker > 0) pendingFlickers.Add(new HiggsfieldDecorDressing.Flicker { Light = component, Amplitude = light.flicker, Seed = ctx.lights * 3.7f });
            }
            if (halo != null)
            {
                Need(ColorUtility.TryParseHtmlString(halo.color, out var color), "Bad halo color " + halo.color);
                color.a = halo.alpha;
                pendingHalos.Add(new HiggsfieldDecorDressing.Halo
                {
                    Anchor = Anchor(placed.go, halo.anchor), Size = halo.size, Color = color, Intensity = halo.intensity,
                    Offset = halo.offset == null ? Vector3.zero : new Vector3(halo.offset[0], halo.offset[1], halo.offset[2])
                });
            }
        }

        static void AttachLightAt(Context ctx, Item item)
        {
            var go = new GameObject("DecorLight_" + item.id);
            go.transform.SetParent(Group(ctx, item.group ?? "Decor_Lights"), false);
            go.transform.position = ctx.instance.transform.TransformPoint(new Vector3(item.at[0], item.at[1], item.at[2]));
            var component = go.AddComponent<Light>();
            component.type = LightType.Point;
            Need(ColorUtility.TryParseHtmlString(item.light.color, out var color), "Bad light color " + item.light.color);
            component.color = color;
            component.intensity = item.light.intensity;
            component.range = Mathf.Min(item.light.range, HiggsfieldMapCatalog.MaximumDecorLightRange);
            component.shadows = LightShadows.None;
            component.bounceIntensity = 0f;
            component.renderMode = LightRenderMode.Auto;
            component.cullingMask &= ~(1 << 30);
            component.lightmapBakeType = LightmapBakeType.Realtime;
            ctx.lights++;
            if (item.light.flicker > 0) pendingFlickers.Add(new HiggsfieldDecorDressing.Flicker { Light = component, Amplitude = item.light.flicker, Seed = ctx.lights * 3.7f });
            if (item.halo != null)
            {
                Need(ColorUtility.TryParseHtmlString(item.halo.color, out var haloColor), "Bad halo color " + item.halo.color);
                haloColor.a = item.halo.alpha;
                pendingHalos.Add(new HiggsfieldDecorDressing.Halo
                {
                    Anchor = go.transform, Size = item.halo.size, Color = haloColor, Intensity = item.halo.intensity,
                    Offset = item.halo.offset == null ? Vector3.zero : new Vector3(item.halo.offset[0], item.halo.offset[1], item.halo.offset[2])
                });
            }
        }

        static Transform Anchor(GameObject go, string name)
        {
            if (string.IsNullOrEmpty(name)) return go.transform;
            var anchor = go.transform.Find(V030PropLibraryImporter.AnchorPrefix + name);
            Need(anchor, "Prop anchor missing: " + go.name + " " + name);
            return anchor;
        }

        // ---------- Validation of a saved decor asset ----------
        /// <summary>Instantiates the map and the saved decor in a fresh scene and re-checks clearance and 2 cm support.</summary>
        public static List<string> ValidateSaved(string mapPrefabPath, string decorPrefabPath, MapConfig mapConfig)
        {
            var problems = new List<string>();
            var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);
            var mapPrefab = AssetDatabase.LoadAssetAtPath<EnvironmentMapDefinition>(mapPrefabPath);
            var decorPrefab = AssetDatabase.LoadAssetAtPath<GameObject>(decorPrefabPath);
            Need(mapPrefab && decorPrefab, "Validation assets missing: " + mapPrefabPath + " / " + decorPrefabPath);
            var map = (EnvironmentMapDefinition)PrefabUtility.InstantiatePrefab(mapPrefab, scene);
            var decor = (GameObject)PrefabUtility.InstantiatePrefab(decorPrefab, scene);
            decor.transform.SetParent(map.transform, false);
            if (decor.GetComponentsInChildren<Collider>(true).Length != 0) problems.Add("decor has colliders");
            var floor = new Regex(mapConfig.floorPattern ?? "^$");
            var path = new Regex(mapConfig.pathPattern ?? "^$");
            var support = new HashSet<Collider>(map.GetComponentsInChildren<Collider>(true).Where(c => !c.isTrigger && !IsBoundary(c.transform)));
            foreach (var renderer in map.GetComponentsInChildren<MeshRenderer>(true))
            {
                if (renderer.GetComponent<Collider>() || !(floor.IsMatch(renderer.name) || path.IsMatch(renderer.name))) continue;
                var filter = renderer.GetComponent<MeshFilter>();
                if (!filter || !filter.sharedMesh) continue;
                var c = renderer.gameObject.AddComponent<MeshCollider>(); c.sharedMesh = filter.sharedMesh; support.Add(c);
            }
            var decorColliders = new Dictionary<Collider, Transform>();
            var props = decor.GetComponentsInChildren<Transform>(true).Where(t => t.name.Split(new[] { Separator }, StringSplitOptions.None).Length == 3).ToArray();
            foreach (var prop in props)
                foreach (var filter in prop.GetComponentsInChildren<MeshFilter>(true))
                {
                    var c = filter.gameObject.AddComponent<MeshCollider>(); c.sharedMesh = filter.sharedMesh; decorColliders[c] = prop;
                }
            Physics.SyncTransforms();
            var keepouts = HiggsfieldDecorClearance.Build(map);
            var openings = Openings(map, new Regex(mapConfig.openingPattern ?? "^$"));
            foreach (var prop in props)
            {
                string mount = prop.name.Split(new[] { Separator }, StringSplitOptions.None)[2];
                Bounds bounds = PrefabBounds(prop.gameObject);
                var violation = HiggsfieldDecorClearance.FirstViolation(bounds, keepouts, (a, b) => Separated(support, a, b));
                if (violation != null) problems.Add(prop.name + ": keep-out " + violation.Kind + " " + violation.Id);
                if (mount == "floor" || mount == "on")
                {
                    Vector3 pivot = prop.position;
                    float nearest = float.MaxValue;
                    foreach (var hit in Physics.RaycastAll(pivot + Vector3.up * 0.3f, Vector3.down, 0.7f, ~0, QueryTriggerInteraction.Ignore))
                    {
                        bool own = decorColliders.TryGetValue(hit.collider, out var owner) && owner == prop;
                        if (own || (!support.Contains(hit.collider) && !decorColliders.ContainsKey(hit.collider))) continue;
                        nearest = Mathf.Min(nearest, Mathf.Abs(hit.point.y - pivot.y));
                    }
                    if (nearest > SupportTolerance) problems.Add(prop.name + ": not resting on a surface (gap " + (nearest == float.MaxValue ? "none" : nearest.ToString("0.000")) + ")");
                }
                else if (mount == "wall")
                {
                    string clash = OpeningClash(openings, bounds);
                    if (clash != null) problems.Add(prop.name + ": " + clash);
                    Vector3 mid = new Vector3(prop.position.x, bounds.center.y, prop.position.z);
                    bool touching = Physics.RaycastAll(mid + prop.forward * 0.05f, -prop.forward, 0.2f, ~0, QueryTriggerInteraction.Ignore)
                        .Any(h => support.Contains(h.collider));
                    if (!touching) problems.Add(prop.name + ": not against a wall");
                }
            }
            Object.DestroyImmediate(map.gameObject);
            return problems;
        }

        // ---------- Spawn view clearance (director r2 #9) ----------
        public const float SpawnEyeHeight = 1.55f;
        // Centre of the first view and the whole 16:9 frame of the gameplay camera (horizontal half-angle ~46 degrees).
        public const float SpawnCenterClearance = 3f, SpawnEdgeClearance = 1.5f;
        public const float SpawnCenterCone = 20f, SpawnEdgeCone = 46f;

        /// <summary>
        /// For every human spawn of every map: how far the first view is free along the catalog's authored yaw, counting the
        /// visible world (map colliders, visual-only map renderers such as foliage, and the saved decor), at eye, chest and
        /// knee height over a +-<see cref="SpawnCenterCone"/> degree cone (>= <see cref="SpawnCenterClearance"/> m) and a
        /// +-<see cref="SpawnEdgeCone"/> cone (>= <see cref="SpawnEdgeClearance"/> m). A blocked spawn gets the nearest clear
        /// yaw as a suggestion; the facings themselves are gameplay data set by the atmosphere config (spawnFacings).
        /// </summary>
        public static JObject SpawnClearanceReport(string output)
        {
            var result = new JObject { ["utc"] = DateTime.UtcNow.ToString("o"), ["cone"] = SpawnCenterCone, ["edgeCone"] = SpawnEdgeCone,
                ["centerClearanceM"] = SpawnCenterClearance, ["edgeClearanceM"] = SpawnEdgeClearance };
            var maps = new JArray();
            EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);
            var catalogIds = AssetDatabase.LoadAssetAtPath<HiggsfieldMapCatalog>(CatalogPath).Entries.Select(e => e.MapId).ToArray();
            foreach (string mapId in catalogIds)
            {
                var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);
                var entry = AssetDatabase.LoadAssetAtPath<HiggsfieldMapCatalog>(CatalogPath).Resolve(mapId);
                var map = (EnvironmentMapDefinition)PrefabUtility.InstantiatePrefab(entry.Prefab, scene);
                if (entry.Decor)
                {
                    var decor = (GameObject)PrefabUtility.InstantiatePrefab(entry.Decor, scene);
                    decor.transform.SetParent(map.transform, false);
                }
                var solid = new HashSet<Collider>();
                foreach (var collider in map.GetComponentsInChildren<Collider>(true))
                    if (!collider.isTrigger && !IsBoundary(collider.transform)) solid.Add(collider);
                foreach (var filter in map.GetComponentsInChildren<MeshFilter>(true))
                {
                    var renderer = filter.GetComponent<MeshRenderer>();
                    if (!renderer || filter.GetComponent<Collider>() || !filter.sharedMesh || IsBoundary(filter.transform)) continue;
                    if (renderer.sharedMaterials.Any(m => m && m.renderQueue >= 2500)) continue; // halos, glass, water sheets
                    if (Regex.IsMatch(filter.name, "(?i)^(water|foam)")) continue;
                    var added = filter.gameObject.AddComponent<MeshCollider>();
                    added.sharedMesh = filter.sharedMesh;
                    solid.Add(added);
                }
                Physics.SyncTransforms();
                var rows = new JArray();
                var points = map.HumanSpawnPoints ?? Array.Empty<Transform>();
                for (int i = 0; i < points.Length; i++)
                {
                    if (!points[i]) continue;
                    var free = new float[180];
                    for (int k = 0; k < 180; k++)
                    {
                        float yaw = k * 2f;
                        Vector3 direction = Quaternion.AngleAxis(yaw, Vector3.up) * Vector3.forward;
                        float nearest = 20f;
                        foreach (float height in new[] { SpawnEyeHeight, 1.0f, 0.5f })
                            foreach (var hit in Physics.RaycastAll(points[i].position + Vector3.up * height, direction, 20f, ~0, QueryTriggerInteraction.Ignore))
                                if (solid.Contains(hit.collider)) nearest = Mathf.Min(nearest, hit.distance);
                        free[k] = nearest;
                    }
                    float Cone(float yaw, float half)
                    {
                        float min = float.MaxValue;
                        for (float d = -half; d <= half + .01f; d += 2f) min = Mathf.Min(min, free[Mathf.RoundToInt(Mathf.Repeat(yaw + d, 360f) / 2f) % 180]);
                        return min;
                    }
                    bool Clear(float yaw) => Cone(yaw, SpawnCenterCone) >= SpawnCenterClearance && Cone(yaw, SpawnEdgeCone) >= SpawnEdgeClearance;
                    bool authored = entry.TryGetSpawnYaw(true, i, out float current);
                    float suggestion = current;
                    if (!Clear(current))
                    {
                        float best = float.NaN;
                        for (int step = 1; step <= 90 && float.IsNaN(best); step++)
                            foreach (float candidate in new[] { current + step * 2f, current - step * 2f })
                                if (Clear(Mathf.Repeat(candidate, 360f))) { best = Mathf.Repeat(candidate, 360f); break; }
                        suggestion = float.IsNaN(best) ? current : best;
                    }
                    // Most open view within 90 degrees of the authored one (what the player first sees, capped at 10 m).
                    float Score(float yaw) => Mathf.Min(10f, Cone(yaw, SpawnEdgeCone)) + .3f * Mathf.Min(10f, Cone(yaw, SpawnCenterCone));
                    float open = current; float openScore = Score(current);
                    for (int step = -45; step <= 45; step++)
                    {
                        float candidate = Mathf.Repeat(current + step * 2f, 360f);
                        float score = Score(candidate) - Mathf.Abs(step) * .002f;
                        if (score > openScore + 1e-3f) { openScore = score; open = candidate; }
                    }
                    rows.Add(new JObject
                    {
                        ["index"] = i, ["authored"] = authored, ["yaw"] = current, ["clear"] = Clear(current),
                        ["openYaw"] = open, ["openCenterFreeM"] = Math.Round(Cone(open, SpawnCenterCone), 2), ["openEdgeFreeM"] = Math.Round(Cone(open, SpawnEdgeCone), 2),
                        ["centerFreeM"] = Math.Round(Cone(current, SpawnCenterCone), 2), ["edgeFreeM"] = Math.Round(Cone(current, SpawnEdgeCone), 2),
                        ["suggestedYaw"] = suggestion, ["suggestedCenterFreeM"] = Math.Round(Cone(suggestion, SpawnCenterCone), 2),
                        ["suggestedEdgeFreeM"] = Math.Round(Cone(suggestion, SpawnEdgeCone), 2)
                    });
                }
                maps.Add(new JObject { ["mapId"] = mapId, ["humanSpawns"] = rows });
            }
            result["maps"] = maps;
            File.WriteAllText(Path.Combine(output, "spawn-clearance.json"), result.ToString(Formatting.Indented) + "\n");
            Debug.Log("LMS_SPAWN_CLEARANCE_REPORT " + Path.Combine(output, "spawn-clearance.json"));
            return result;
        }

        // ---------- Helpers ----------
        static IEnumerable<Vector2> Spiral(float radius, float step)
        {
            yield return Vector2.zero;
            if (radius <= 0) yield break;
            for (float r = step; r <= radius + 1e-4f; r += step)
            {
                int n = Mathf.Max(6, Mathf.RoundToInt(2 * Mathf.PI * r / step));
                for (int i = 0; i < n; i++) { float a = i * 2 * Mathf.PI / n; yield return new Vector2(Mathf.Cos(a), Mathf.Sin(a)) * r; }
            }
        }

        static Transform Group(Context ctx, string name)
        {
            if (ctx.groups.TryGetValue(name, out var group)) return group;
            group = new GameObject(name).transform;
            group.SetParent(ctx.root.transform, false);
            ctx.groups[name] = group;
            return group;
        }

        static readonly Dictionary<string, GameObject> propCache = new Dictionary<string, GameObject>(StringComparer.Ordinal);
        static GameObject PropPrefab(string prop)
        {
            if (propCache.TryGetValue(prop, out var cached) && cached) return cached;
            var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(V030PropLibraryImporter.PrefabsRoot + "/Prop_" + prop + ".prefab");
            Need(prefab, "Library prop missing: " + prop);
            propCache[prop] = prefab;
            return prefab;
        }

        public static Bounds PrefabBounds(GameObject go)
        {
            var renderers = go.GetComponentsInChildren<Renderer>(true);
            if (renderers.Length == 0) return new Bounds(go.transform.position, Vector3.zero);
            var bounds = renderers[0].bounds;
            foreach (var r in renderers) bounds.Encapsulate(r.bounds);
            return bounds;
        }

        static void EnsureFolder(string folder)
        {
            if (AssetDatabase.IsValidFolder(folder)) return;
            string parent = Path.GetDirectoryName(folder).Replace('\\', '/');
            EnsureFolder(parent);
            AssetDatabase.CreateFolder(parent, Path.GetFileName(folder));
        }

        static void Need(bool condition, string message) { if (!condition) throw new InvalidOperationException(message); }
    }
}
