using System.IO;
using TMPro;
using UnityEditor;
using UnityEngine;
using UnityEngine.TextCore.LowLevel;

namespace LetMeSleep.Editor
{
    /// <summary>
    /// Builds the v0.3 UI display face asset that AlfaUiTheme loads from Resources (no scene reference):
    /// Assets/LetMeSleep/UI/Resources/AlfaUiFonts/LMSBarlowNarrow-Bold SDF.asset from the TTF generated by
    /// docs/unity/ui/tools/build_ui_fonts.py. Dynamic SDF like the alpha faces, Spanish glyphs pre-added.
    /// Batch: -batchmode -quit -executeMethod LetMeSleep.Editor.AlfaUiFontAssetBuilder.Build
    /// </summary>
    public static class AlfaUiFontAssetBuilder
    {
        private const string SourcePath = "Assets/LetMeSleep/UI/Fonts/LMSBarlowNarrow-Bold.ttf";
        private const string Folder = "Assets/LetMeSleep/UI/Resources/AlfaUiFonts";
        private const string AssetPath = Folder + "/LMSBarlowNarrow-Bold SDF.asset";
        private const string Characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 áéíóúüñÁÉÍÓÚÜÑ¿¡?!·…:;,./-_()+%×–—'\"#&*<>=@";

        [MenuItem("Let me sleep/UI/Rebuild or clear display font asset")]
        public static void Build()
        {
            var source = AssetDatabase.LoadAssetAtPath<Font>(SourcePath);
            if (source == null) throw new FileNotFoundException(SourcePath);
            if (!AssetDatabase.IsValidFolder("Assets/LetMeSleep/UI/Resources")) AssetDatabase.CreateFolder("Assets/LetMeSleep/UI", "Resources");
            if (!AssetDatabase.IsValidFolder(Folder)) AssetDatabase.CreateFolder("Assets/LetMeSleep/UI/Resources", "AlfaUiFonts");
            var existing = AssetDatabase.LoadAssetAtPath<TMP_FontAsset>(AssetPath);
            if (existing != null)
            {
                // Keep the GUID: drop the glyphs that play mode baked into the dynamic atlas.
                existing.ClearFontAssetData(true);
                EditorUtility.SetDirty(existing);
                AssetDatabase.SaveAssets();
                Debug.Log("LMS_UI_FONT_ASSET_CLEARED " + AssetPath);
                return;
            }
            var font = TMP_FontAsset.CreateFontAsset(source, 72, 9, GlyphRenderMode.SDFAA, 1024, 1024, AtlasPopulationMode.Dynamic, true);
            font.name = "LMSBarlowNarrow-Bold SDF";
            AssetDatabase.CreateAsset(font, AssetPath);
            foreach (var texture in font.atlasTextures)
            {
                texture.name = font.name + " Atlas";
                AssetDatabase.AddObjectToAsset(texture, font);
            }
            font.material.name = font.name + " Material";
            AssetDatabase.AddObjectToAsset(font.material, font);
            font.TryAddCharacters(Characters, out var missing);
            if (!string.IsNullOrEmpty(missing)) Debug.LogWarning("LMS_UI_FONT_MISSING_GLYPHS " + missing);
            EditorUtility.SetDirty(font);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log("LMS_UI_FONT_ASSET_BUILT " + AssetPath + " glyphs=" + font.characterTable.Count);
        }
    }
}
